- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:  
  
  - name: set root password
    user:
      name: root
      password: "{{ su_password | password_hash('sha512') }}"
     
  - name: copy the controller tar archive to the remote host
    copy:
      src: "/opt/controller_license.txt"
      dest: "/opt/controller_license.txt"
      owner: ubuntu
      group: ubuntu
      force: yes

- name: Retrieve the NGINX Controller auth token
  hosts: all
  
  collections:
    - nginxinc.nginx_controller
 
  roles:
    - nginxinc.nginx_controller_generate_token
      
- name: Push the NGINX Controller license to your instance
  hosts: all
  
  roles:
    - nginxinc.nginx_controller_license
  
  vars:
    nginx_controller_license: "{{ lookup('file', '/opt/controller_license.txt') | b64encode }}"
