- hosts: all
  remote_user: azureuser
  become: yes
  become_method: sudo
  gather_facts: yes

  vars:
    nginx_controller_user_email: "p.holland@f5.com"
    nginx_controller_user_password: "sc00byd00"
    nginx_controller_fqdn: "nginxcontroller.northeurope.cloudapp.azure.com"
    nginx_controller_validate_certs: false
  
  tasks: 

- name: Retrieve the NGINX Controller auth token  
  hosts: all
  
  collections:
    - nginxinc.nginx_controller
  
  roles:
    - nginxinc.nginx_controller_generate_token
      
- name: Push the NGINX Controller license to your instance
  hosts: all
  
  roles:
    - nginxinc.nginx_controller_license
  
  vars:
        # controller.auth_token: output by previous role in example
        nginx_controller_license: "{{ lookup('file', '/home/azureuser/controller_license.txt') | b64encode }}"
