- hosts: all
  remote_user: azureuser
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:  
  
  - name: set root password
    user:
      name: root
      password: "{{ su_password | password_hash('sha512') }}"
     
  - name: copy the controller tar archive to the remote host
    copy:
      src: "/opt/{{nginx_controller_tarball}}"
      dest: "/opt/{{nginx_controller_tarball}}"
      owner: azureuser
      group: azureuser
      force: yes
    vars:
      nginx_controller_install_path: "{{ ansible_env.HOME }}"
      nginx_controller_tarball: "controller-installer-3.9.0.tar"
      
  - name:  make sure all the prerequisites are present on the remote
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - gettext
      - bash
      - gzip
      - coreutils
      - grep
      - less
      - sed
      - tar
      - python-pexpect  # to support ansible
      - nfs-common  # to support nfs remote volume
    tags: packages
