- name: DEPLOY
  hosts: all
  gather_facts: yes
  remote_user: azureuser
  become: yes
  become_method: sudo
  
- name: set root password to support su for Controller installation with Ubuntu
  user:
    name: root
    password: "{{ su_password | password_hash('sha512') }}"
