- hosts: all
  remote_user: azureuser
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:

  - name: set root password
    user:
      name: root
      password: "{{ su_password | password_hash('sha512') }}"
     
  - name: copy the controller tar archive to the remote host
    copy:
      src: "{{playbook_dir}}/{{nginx_controller_tarball}}"
      dest: "{{ ansible_env.HOME }}/{{nginx_controller_tarball}}"
      owner: ubuntu
      group: ubuntu
      force: yes
    vars:
      nginx_controller_install_path: "{{ ansible_env.HOME }}"
      nginx_controller_tarball: "controller-installer-<>.tar.gz"
