- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    nginx_controller_user_email: "pholland@f5.com"
    nginx_controller_user_password: "Ehkh1237jjbj"
    nginx_controller_fqdn: "35.178.189.92"
    nginx_controller_validate_certs: false

  tasks:
  - include_role:
      name: nginxinc.nginx_controller.nginx_controller_generate_token

  - name: Get controller api key for agent registration
    uri:
      url: "https://{{ nginx_controller_fqdn }}/api/v1/platform/global"
      method: "GET"
      return_content: yes
      status_code: 200
      validate_certs: false
      headers:
        Cookie: "{{nginx_controller_auth_token}}"
    register: ctrl_globals

  - name: Copy api_key to a variable
    set_fact:
      api_key: "{{ctrl_globals.json.currentStatus.agentSettings.apiKey}}"

- hosts: nginxservers
  remote_user: ec2-user
  become: true
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_ssh_private_key_file: "~/.ssh/my_aws"

  tasks:
#   - name: install minimal support for python2 for Agent install script
#     yum:
#       name: "{{ packages }}"
#       state: present
#     vars:
#       packages:
#  #     - python-minimal
#       - libxerces-c3.2

  - name: install the agent
    include_role:
      name: nginxinc.nginx_controller.nginx_controller_agent
    vars:
      nginx_controller_api_key: "{{ hostvars['localhost']['api_key'] }}"
      nginx_controller_fqdn: "10.9.10.7"
